# Generated by Django 3.2.7 on 2021-10-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedata',
            name='owner',
            field=models.CharField(max_length=30),
        ),
    ]
